<?php $_menu = $this->getHtml('level-top') ?>
<?php if ($_menu): ?>
    <div class="container">
        <nav class="navbar navbar-default navbar-main" role="navigation">
            <div class="navbar-header">
                <a class="navbar-brand" href="#" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <?php echo $this->__('Categories') ?>
                </a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <span class="sr-only"><?php echo $this->__('Toggle Navigation') ?></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <?php echo $_menu ?>
                </ul>
            </div>
        </nav>
    </div>
<?php endif ?>

